// packages/vue/src/select/TulparOptionGroup.vue
<script setup lang="ts">
/**
 * TulparOptionGroup — groups `<tulpar-option>` children under a header (v0.14).
 *
 * Renders a `<tulpar-option-group>` web component. Forwards the `label` prop
 * as an attribute and the `label` named slot through a display:contents carrier
 * so the core's shadow `<slot name="label">` receives it correctly.
 * The default slot projects `<tulpar-option>` children naturally.
 */
import "@tulpar-ui/core/select";

interface Props {
  /** Convenience label (alias of the `label` slot). Slot wins when both set. */
  label?: string;
}

const { label } = defineProps<Props>();
</script>

<template>
  <tulpar-option-group :label="label ?? undefined">
    <!-- Named slot carrier for the group header label. -->
    <span v-if="$slots.label" style="display: contents" slot="label"><slot name="label" /></span>
    <!-- Default slot: projects <tulpar-option> children. -->
    <slot />
  </tulpar-option-group>
</template>

// packages/angular/src/select/tulpar-option-group.component.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA, input } from "@angular/core";

import "@tulpar-ui/core/select";

/**
 * Angular signal wrapper for `<tulpar-option-group>` — groups
 * `<tulpar-option-ng>` children under a header label.
 *
 * Forwards `label` as an attribute. Slot projection: `slot="label"` is
 * forwarded via a named `<ng-content>` selector; the default slot projects
 * child options.
 *
 * NO RxJS — signals only.
 */
@Component({
  selector: "tulpar-option-group-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-option-group [attr.label]="label() ?? null">
      <ng-content select="[slot='label']" />
      <ng-content />
    </tulpar-option-group>
  `,
})
export class TulparOptionGroupComponent {
  /** Convenience label for the group header (alias of `slot="label"`). Slot wins. */
  readonly label = input<string | undefined>(undefined);
}
