// packages/angular/src/checkbox-group/tulpar-checkbox-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  model,
  output,
} from "@angular/core";

import "@tulpar-ui/core/checkbox-group";

import type { SelectionSize } from "@tulpar-ui/core/checkbox-group";

export type { SelectionSize };

/**
 * Angular signal wrapper for `<tulpar-checkbox-group>`.
 *
 * Group nesting note: this wrapper uses `display:contents` so the core
 * `<tulpar-checkbox-group>` element is the direct DOM parent of any projected
 * `<tulpar-checkbox>` (or `<tulpar-checkbox-ng>`) children. The core group
 * queries children via descendant selector for `tulpar-checkbox`, so the core
 * elements must remain descendants of the core group — this `display:contents`
 * host ensures that.
 *
 * Two-way binding: use `[(value)]="myArray"` — synced via the group's composed
 * `change` CustomEvent `detail.value` (string[]).
 * NO RxJS — signals only.
 */
@Component({
  selector: "tulpar-checkbox-group-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-checkbox-group
      [value]="value()"
      [attr.name]="name() ?? null"
      [attr.orientation]="orientation()"
      [attr.size]="size()"
      [attr.label]="label() ?? null"
      [attr.disabled]="disabled() ? '' : null"
      [attr.readonly]="readonly() ? '' : null"
      [attr.required]="required() ? '' : null"
      [attr.invalid]="invalid() ? '' : null"
      [attr.warn]="warn() ? '' : null"
      [attr.helper-text]="helperText() ?? null"
      [attr.error-text]="errorText() ?? null"
      [attr.warn-text]="warnText() ?? null"
      [attr.no-message-space]="noMessageSpace() ? '' : null"
      [attr.color]="color() ?? null"
      [attr.description]="description() ?? null"
      (change)="onCoreChange($event)"
    >
      <ng-content select="[slot='label']" />
      <ng-content select="[slot='description']" />
      <ng-content />
    </tulpar-checkbox-group>
  `,
})
export class TulparCheckboxGroupComponent {
  // Two-way (array value)
  readonly value = model<string[]>([]);

  // Group props
  readonly name = input<string | undefined>(undefined);
  readonly orientation = input<"vertical" | "horizontal">("vertical");
  readonly size = input<SelectionSize>("md");
  readonly label = input<string | undefined>(undefined);
  readonly disabled = input<boolean>(false);
  readonly readonly = input<boolean>(false);
  readonly required = input<boolean>(false);
  readonly invalid = input<boolean>(false);
  readonly warn = input<boolean>(false);
  readonly helperText = input<string | undefined>(undefined);
  readonly errorText = input<string | undefined>(undefined);
  readonly warnText = input<string | undefined>(undefined);
  readonly noMessageSpace = input<boolean>(false);
  readonly color = input<string | undefined>(undefined);
  readonly description = input<string | undefined>(undefined);

  readonly change = output<CustomEvent<{ value: string[] }>>();

  onCoreChange(e: Event) {
    const ce = e as CustomEvent<{ value: string[] }>;
    if (ce.detail && "value" in ce.detail) {
      this.value.set(ce.detail.value);
      this.change.emit(ce);
    }
  }
}

// packages/vue/src/checkbox-group/TulparCheckboxGroup.vue
<script setup lang="ts">
import "@tulpar-ui/core/checkbox-group";
import type { SelectionSize } from "@tulpar-ui/core/checkbox-group";

/**
 * Group nesting: this wrapper uses `display:contents` (via the core element
 * style) so projected `<tulpar-checkbox>` children remain DOM descendants of
 * the core `<tulpar-checkbox-group>`. The core group queries children via a
 * descendant selector, so the core elements must not be blocked by an
 * intervening opaque host.
 *
 * v-model: string[] — synced via the group's composed `change`
 * CustomEvent `detail.value`.
 */
interface Props {
  modelValue?: string[];
  name?: string;
  orientation?: "vertical" | "horizontal";
  size?: SelectionSize;
  label?: string;
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  invalid?: boolean;
  warn?: boolean;
  helperText?: string;
  errorText?: string;
  warnText?: string;
  noMessageSpace?: boolean;
  color?: string;
}

const {
  orientation = "vertical",
  size = "md",
} = defineProps<Props>();

const emit = defineEmits<{
  "update:modelValue": [value: string[]];
  change: [event: CustomEvent<{ value: string[] }>];
}>();

function onChange(e: Event) {
  const ce = e as CustomEvent<{ value: string[] }>;
  if (ce.detail && "value" in ce.detail) {
    emit("update:modelValue", ce.detail.value);
    emit("change", ce);
  }
}
</script>

<template>
  <tulpar-checkbox-group
    :name="name ?? undefined"
    :orientation="orientation"
    :size="size"
    :label="label ?? undefined"
    :disabled="disabled || undefined"
    :readonly="readonly || undefined"
    :required="required || undefined"
    :invalid="invalid || undefined"
    :warn="warn || undefined"
    :helper-text="helperText ?? undefined"
    :error-text="errorText ?? undefined"
    :warn-text="warnText ?? undefined"
    :no-message-space="noMessageSpace || undefined"
    :color="color ?? undefined"
    @change="onChange"
  >
    <slot name="label" />
    <slot name="description" />
    <slot />
  </tulpar-checkbox-group>
</template>
