// packages/angular/src/shell/tulpar-sidenav.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  type Type,
  computed,
  effect,
  inject,
  input,
  output,
} from "@angular/core";

import { NgComponentOutlet, NgTemplateOutlet } from "@angular/common";

import "@tulpar-ui/shell";
import type { TulparNavItemData, TulparSidenav } from "@tulpar-ui/shell";

import { TulparNavItemComponent } from "./tulpar-nav-item.component";
import { TulparNavSectionComponent } from "./tulpar-nav-section.component";

export type { TulparNavItemData };

/**
 * Angular-flavoured nav item data. Identical to the core {@link TulparNavItemData}
 * except `icon` may also be an Angular component `Type` — when a component is
 * supplied the wrapper projects it through a slotted `<span slot="icon">` rather
 * than handing the array to the web component (which only understands SVG strings).
 */
export interface TulparNavItemNgData extends Omit<TulparNavItemData, "icon" | "items"> {
  icon?: string | Type<unknown>;
  items?: TulparNavItemNgData[];
}

function hasComponentIcon(items: TulparNavItemNgData[] | undefined): boolean {
  if (!items) return false;
  return items.some(
    (i) => (i.icon != null && typeof i.icon !== "string") || hasComponentIcon(i.items),
  );
}

@Component({
  selector: "tulpar-sidenav-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [
    NgComponentOutlet,
    NgTemplateOutlet,
    TulparNavItemComponent,
    TulparNavSectionComponent,
  ],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-sidenav
      [attr.nav-label]="navLabel() ?? null"
      [attr.position]="position()"
      [attr.density]="density()"
      [attr.single-expand]="singleExpand() ? '' : null"
      [attr.toggle-label]="toggleLabel() ?? null"
      [attr.search-placeholder]="searchPlaceholder() ?? null"
      [attr.search-label]="searchLabel() ?? null"
      [attr.search-empty-text]="searchEmptyText() ?? null"
      [attr.show-mode-selection]="showModeSelection() ? '' : null"
      [attr.show-config]="showConfig() ? '' : null"
      [attr.config-text]="configText() ?? null"
      [attr.theme-label]="themeLabel() ?? null"
      [attr.theme-text-dark]="themeTextDark() ?? null"
      [attr.theme-text-light]="themeTextLight() ?? null"
      [attr.config-label]="configLabel() ?? null"
      [attr.show-account-block]="showAccountBlock() ? '' : null"
      [attr.user-name]="userName() ?? null"
      [attr.user-role]="userRole() ?? null"
      [attr.profile-image]="profileImage() ?? null"
      [attr.show-settings]="showSettings() ? '' : null"
      [attr.show-logout]="showLogout() ? '' : null"
      [attr.settings-label]="settingsLabel() ?? null"
      [attr.logout-label]="logoutLabel() ?? null"
      (tulpar-config-click)="config.emit()"
      (tulpar-settings-click)="settings.emit()"
      (tulpar-logout)="logout.emit()"
    >
      <ng-content select="[slot='header']" />
      <ng-content select="[slot='header-actions']" />
      <ng-content select="[slot='search']" />
      <ng-content select="[slot='utility-start']" />
      <ng-content select="[slot='utility-end']" />
      @if (renderItemsInLightDom()) {
        @for (item of items(); track $index) {
          <ng-container [ngTemplateOutlet]="itemTpl" [ngTemplateOutletContext]="{ $implicit: item }" />
        }
      }
      <ng-content />
      <ng-content select="[slot='footer']" />
    </tulpar-sidenav>

    <ng-template #itemTpl let-item>
      @if (item.type === "section") {
        <tulpar-nav-section-ng [label]="item.label">
          @for (child of item.items; track $index) {
            <ng-container
              [ngTemplateOutlet]="itemTpl"
              [ngTemplateOutletContext]="{ $implicit: child }"
            />
          }
        </tulpar-nav-section-ng>
      } @else {
        <tulpar-nav-item-ng
          [href]="item.href"
          [label]="item.label"
          [icon]="isStringIcon(item.icon) ? item.icon : undefined"
          [iconClass]="item.iconClass"
          [badge]="item.badge"
          [count]="item.count"
          [dot]="item.dot ?? false"
          [dotLabel]="item.dotLabel"
          [kbd]="item.kbd"
          [target]="item.target"
          [active]="item.active ?? false"
          [disabled]="item.disabled ?? false"
        >
          @if (item.icon && !isStringIcon(item.icon)) {
            <span slot="icon">
              <ng-container [ngComponentOutlet]="item.icon" />
            </span>
          }
          @for (child of item.items; track $index) {
            <ng-container
              [ngTemplateOutlet]="itemTpl"
              [ngTemplateOutletContext]="{ $implicit: child }"
            />
          }
        </tulpar-nav-item-ng>
      }
    </ng-template>
  `,
})
export class TulparSidenavComponent {
  /**
   * Menu data. Items whose `icon` is a string (or absent) are handed to the web
   * component as a DOM property. If ANY item carries a component `icon`, the
   * whole tree is instead rendered in light DOM so the component can be projected
   * through `<span slot="icon">` (web components cannot host Angular components).
   */
  readonly items = input<TulparNavItemNgData[] | undefined>(undefined);
  readonly navLabel = input<string | undefined>(undefined);
  readonly position = input<"left" | "right">("left");
  readonly density = input<"comfortable" | "compact">("comfortable");
  readonly singleExpand = input<boolean>(false);

  readonly showSearch = input<boolean>(true);
  readonly searchPlaceholder = input<string | undefined>(undefined);
  readonly searchLabel = input<string | undefined>(undefined);
  readonly searchEmptyText = input<string | undefined>(undefined);

  readonly toggleLabel = input<string | undefined>(undefined);
  readonly showModeSelection = input<boolean>(true);
  readonly showConfig = input<boolean>(false);
  readonly configText = input<string | undefined>(undefined);
  readonly themeLabel = input<string | undefined>(undefined);
  readonly themeTextDark = input<string | undefined>(undefined);
  readonly themeTextLight = input<string | undefined>(undefined);
  readonly configLabel = input<string | undefined>(undefined);

  readonly showAccountBlock = input<boolean>(true);
  readonly userName = input<string | undefined>(undefined);
  readonly userRole = input<string | undefined>(undefined);
  readonly profileImage = input<string | undefined>(undefined);
  readonly showSettings = input<boolean>(false);
  readonly showLogout = input<boolean>(true);
  readonly settingsLabel = input<string | undefined>(undefined);
  readonly logoutLabel = input<string | undefined>(undefined);

  readonly config = output<void>();
  readonly settings = output<void>();
  readonly logout = output<void>();

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);

  /**
   * True when items must be rendered in light DOM (component icons present).
   * Memoised as a computed signal so the `hasComponentIcon` tree traversal is
   * shared between the template `@if` and the `effect()` read sites.
   */
  readonly renderItemsInLightDom = computed(() => hasComponentIcon(this.items()));

  isStringIcon(icon: unknown): icon is string {
    return typeof icon === "string";
  }

  constructor() {
    // `items` is a DOM property (not an attribute) — set it on the element, but
    // ONLY when we're delegating to the web component. When component icons force
    // light-DOM rendering we must NOT also set the property (would double-render).
    effect(() => {
      const el = this.host.nativeElement.querySelector<TulparSidenav>("tulpar-sidenav");
      if (!el) return;
      el.items = this.renderItemsInLightDom()
        ? undefined
        : (this.items() as TulparNavItemData[] | undefined);
      // `showSearch` defaults to true in the element; set it as a DOM property so
      // `false` actually disables the search (an absent boolean attribute would
      // leave the element's `true` default in place).
      el.showSearch = this.showSearch();
    });
  }
}

// packages/vue/src/shell/TulparSidenav.vue
<script setup lang="ts">
import "@tulpar-ui/shell";
import {
  computed,
  defineComponent,
  h,
  ref,
  watchEffect,
  type Component,
  type PropType,
  type VNode,
} from "vue";
import type { TulparNavItemData, TulparSidenav as TulparSidenavEl } from "@tulpar-ui/shell";
import TulparNavItem from "./TulparNavItem.vue";
import TulparNavSection from "./TulparNavSection.vue";

/**
 * Vue-flavoured nav item data. Identical to the core {@link TulparNavItemData}
 * except `icon` may also be a Vue component — when a component is supplied the
 * wrapper projects it through a slotted `<span slot="icon">` rather than handing
 * the array to the web component (which only understands SVG strings).
 */
export interface TulparNavItemVueData extends Omit<TulparNavItemData, "icon" | "items"> {
  icon?: string | Component;
  items?: TulparNavItemVueData[];
}

interface Props {
  items?: TulparNavItemVueData[];
  navLabel?: string;
  position?: "left" | "right";
  density?: "comfortable" | "compact";
  singleExpand?: boolean;
  showSearch?: boolean;
  searchPlaceholder?: string;
  searchLabel?: string;
  searchEmptyText?: string;
  toggleLabel?: string;
  showModeSelection?: boolean;
  showConfig?: boolean;
  configText?: string;
  themeLabel?: string;
  themeTextDark?: string;
  themeTextLight?: string;
  configLabel?: string;
  showAccountBlock?: boolean;
  userName?: string;
  userRole?: string;
  profileImage?: string;
  showSettings?: boolean;
  showLogout?: boolean;
  settingsLabel?: string;
  logoutLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  position: "left",
  density: "comfortable",
  singleExpand: false,
  showSearch: true,
  showModeSelection: true,
  showConfig: false,
  showAccountBlock: true,
  showSettings: false,
  showLogout: true,
});

const emit = defineEmits<{
  config: [];
  settings: [];
  logout: [];
}>();

function isStringIcon(icon: unknown): icon is string {
  return typeof icon === "string";
}

function hasComponentIcon(items: TulparNavItemVueData[] | undefined): boolean {
  if (!items) return false;
  return items.some((i) => (i.icon != null && !isStringIcon(i.icon)) || hasComponentIcon(i.items));
}

// When any item carries a component icon, render the whole tree in light DOM so
// the component can be projected through `<span slot="icon">`. Otherwise delegate
// the array to the web component (existing behaviour, preserves rendering).
const renderItemsInLightDom = computed(() => hasComponentIcon(props.items));

// Recursive renderer used only for the light-DOM path. String icons pass through
// to the `icon` prop; component icons project into the `icon` slot.
const NavNode = defineComponent({
  name: "TulparNavNode",
  props: { item: { type: Object as PropType<TulparNavItemVueData>, required: true } },
  setup(p) {
    const renderChildren = (children?: TulparNavItemVueData[]): VNode[] =>
      (children ?? []).map((c, i) => h(NavNode, { item: c, key: c.href ?? c.label ?? i }));

    return () => {
      const item = p.item;
      if (item.type === "section") {
        return h(TulparNavSection, { label: item.label }, () => renderChildren(item.items));
      }
      const isString = isStringIcon(item.icon);
      // The TulparNavItem SFC exposes only a default <slot/>; the underlying web
      // component has a named <slot name="icon">. So a component icon is rendered
      // as a default-slot child carrying the `slot="icon"` attribute, which the
      // browser then distributes to the WC's icon slot.
      const slots: Record<string, () => VNode[]> = {
        default: () => [
          ...(item.icon && !isString
            ? [h("span", { slot: "icon" }, [h(item.icon as Component)])]
            : []),
          ...renderChildren(item.items),
        ],
      };
      return h(
        TulparNavItem,
        {
          href: item.href,
          label: item.label,
          icon: isString ? (item.icon as string) : undefined,
          iconClass: item.iconClass,
          badge: item.badge,
          count: item.count,
          dot: item.dot ?? false,
          dotLabel: item.dotLabel,
          kbd: item.kbd,
          target: item.target,
          active: item.active ?? false,
          disabled: item.disabled ?? false,
        },
        slots,
      );
    };
  },
});

// `items` is attribute: false on the WC — set it as a JS property. Skip when we
// render in light DOM (would double-render).
const hostRef = ref<TulparSidenavEl | null>(null);
watchEffect(() => {
  if (!hostRef.value) return;
  hostRef.value.items = renderItemsInLightDom.value
    ? undefined
    : (props.items as TulparNavItemData[] | undefined);
  // `showSearch` defaults to true in the element; set it as a DOM property so
  // `false` actually disables it (an absent boolean attribute keeps the default).
  hostRef.value.showSearch = props.showSearch;
});
</script>

<template>
  <tulpar-sidenav
    ref="hostRef"
    :nav-label="navLabel ?? undefined"
    :position="position"
    :density="density"
    :single-expand="singleExpand || undefined"
    :search-placeholder="searchPlaceholder ?? undefined"
    :search-label="searchLabel ?? undefined"
    :search-empty-text="searchEmptyText ?? undefined"
    :toggle-label="toggleLabel ?? undefined"
    :show-mode-selection="showModeSelection || undefined"
    :show-config="showConfig || undefined"
    :config-text="configText ?? undefined"
    :theme-label="themeLabel ?? undefined"
    :theme-text-dark="themeTextDark ?? undefined"
    :theme-text-light="themeTextLight ?? undefined"
    :config-label="configLabel ?? undefined"
    :show-account-block="showAccountBlock || undefined"
    :user-name="userName ?? undefined"
    :user-role="userRole ?? undefined"
    :profile-image="profileImage ?? undefined"
    :show-settings="showSettings || undefined"
    :show-logout="showLogout || undefined"
    :settings-label="settingsLabel ?? undefined"
    :logout-label="logoutLabel ?? undefined"
    @tulpar-config-click="emit('config')"
    @tulpar-settings-click="emit('settings')"
    @tulpar-logout="emit('logout')"
  >
    <span style="display: contents" slot="header"><slot name="header" /></span>
    <span style="display: contents" slot="header-actions"><slot name="header-actions" /></span>
    <span style="display: contents" slot="search"><slot name="search" /></span>
    <span style="display: contents" slot="utility-start"><slot name="utility-start" /></span>
    <span style="display: contents" slot="utility-end"><slot name="utility-end" /></span>
    <template v-if="renderItemsInLightDom">
      <NavNode v-for="(item, i) in items" :key="item.href ?? item.label ?? i" :item="item" />
    </template>
    <slot />
    <span style="display: contents" slot="footer"><slot name="footer" /></span>
  </tulpar-sidenav>
</template>
