// packages/angular/src/radio-group/tulpar-radio-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  model,
  output,
} from "@angular/core";

import "@tulpar-ui/core/radio-group";

import type { SelectionSize } from "@tulpar-ui/core/radio-group";

export type { SelectionSize };

/**
 * Angular signal wrapper for `<tulpar-radio-group>`.
 *
 * Group nesting note: this wrapper uses `display:contents` so the core
 * `<tulpar-radio-group>` element is the direct DOM parent of any projected
 * `<tulpar-radio>` (or `<tulpar-radio-ng>`) children. The core group queries
 * children via descendant selector for `tulpar-radio`, so the core elements
 * must remain descendants of the core group — this `display:contents` host
 * ensures that.
 *
 * Two-way binding: use `[(value)]="myString"` — synced via the group's
 * composed `change` CustomEvent `detail.value`.
 * NO RxJS — signals only.
 */
@Component({
  selector: "tulpar-radio-group-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-radio-group
      [attr.value]="value() ?? null"
      [attr.name]="name() ?? null"
      [attr.orientation]="orientation()"
      [attr.size]="size()"
      [attr.label]="label() ?? null"
      [attr.disabled]="disabled() ? '' : null"
      [attr.readonly]="readonly() ? '' : null"
      [attr.required]="required() ? '' : null"
      [attr.invalid]="invalid() ? '' : null"
      [attr.warn]="warn() ? '' : null"
      [attr.helper-text]="helperText() ?? null"
      [attr.error-text]="errorText() ?? null"
      [attr.warn-text]="warnText() ?? null"
      [attr.no-message-space]="noMessageSpace() ? '' : null"
      [attr.color]="color() ?? null"
      (change)="onCoreChange($event)"
    >
      <ng-content select="[slot='label']" />
      <ng-content select="[slot='description']" />
      <ng-content />
    </tulpar-radio-group>
  `,
})
export class TulparRadioGroupComponent {
  // Two-way
  readonly value = model<string | null>(null);

  // Group props
  readonly name = input<string | undefined>(undefined);
  readonly orientation = input<"vertical" | "horizontal">("vertical");
  readonly size = input<SelectionSize>("md");
  readonly label = input<string | undefined>(undefined);
  readonly disabled = input<boolean>(false);
  readonly readonly = input<boolean>(false);
  readonly required = input<boolean>(false);
  readonly invalid = input<boolean>(false);
  readonly warn = input<boolean>(false);
  readonly helperText = input<string | undefined>(undefined);
  readonly errorText = input<string | undefined>(undefined);
  readonly warnText = input<string | undefined>(undefined);
  readonly noMessageSpace = input<boolean>(false);
  readonly color = input<string | undefined>(undefined);

  readonly change = output<CustomEvent<{ value: string | null }>>();

  onCoreChange(e: Event) {
    const ce = e as CustomEvent<{ value: string | null }>;
    if (ce.detail && "value" in ce.detail) {
      this.value.set(ce.detail.value);
      this.change.emit(ce);
    }
  }
}

// packages/vue/src/radio-group/TulparRadioGroup.vue
<script setup lang="ts">
import "@tulpar-ui/core/radio-group";
import type { SelectionSize } from "@tulpar-ui/core/radio-group";

/**
 * Group nesting: this wrapper uses `display:contents` (via the core element
 * style) so projected `<tulpar-radio>` children remain DOM descendants of
 * the core `<tulpar-radio-group>`. The core group queries children via a
 * descendant selector, so the core elements must not be blocked by an
 * intervening opaque host.
 *
 * v-model: string | null — synced via the group's composed `change`
 * CustomEvent `detail.value`.
 */
interface Props {
  modelValue?: string | null;
  name?: string;
  orientation?: "vertical" | "horizontal";
  size?: SelectionSize;
  label?: string;
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  invalid?: boolean;
  warn?: boolean;
  helperText?: string;
  errorText?: string;
  warnText?: string;
  noMessageSpace?: boolean;
  color?: string;
}

const {
  modelValue = null,
  orientation = "vertical",
  size = "md",
} = defineProps<Props>();

const emit = defineEmits<{
  "update:modelValue": [value: string | null];
  change: [event: CustomEvent<{ value: string | null }>];
}>();

function onChange(e: Event) {
  const ce = e as CustomEvent<{ value: string | null }>;
  if (ce.detail && "value" in ce.detail) {
    emit("update:modelValue", ce.detail.value);
    emit("change", ce);
  }
}
</script>

<template>
  <tulpar-radio-group
    :value="modelValue ?? undefined"
    :name="name ?? undefined"
    :orientation="orientation"
    :size="size"
    :label="label ?? undefined"
    :disabled="disabled || undefined"
    :readonly="readonly || undefined"
    :required="required || undefined"
    :invalid="invalid || undefined"
    :warn="warn || undefined"
    :helper-text="helperText ?? undefined"
    :error-text="errorText ?? undefined"
    :warn-text="warnText ?? undefined"
    :no-message-space="noMessageSpace || undefined"
    :color="color ?? undefined"
    @change="onChange"
  >
    <slot name="label" />
    <slot name="description" />
    <slot />
  </tulpar-radio-group>
</template>
