// packages/vue/src/shell/TulparShell.vue
<script setup lang="ts">
import "@tulpar-ui/shell";
import { getCurrentInstance, onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { ShellSidenavMode, ShellState, TulparShell as TulparShellEl } from "@tulpar-ui/shell";
import { persistShellState } from "@tulpar-ui/shell";

// Minimal structural type for the bits of a vue-router instance we use. We never
// import `vue-router` statically — that would force router-less apps to install
// it (the externalized bare import would fail to resolve at runtime). Instead we
// resolve it dynamically below; when absent, the nav-item's native <a> takes over.
interface RouterLike {
  push: (to: string) => unknown;
  afterEach: (hook: () => void) => () => void;
}

interface Props {
  sidenavMode?: ShellSidenavMode;
  sidenavLayout?: "under-topbar" | "over-topbar";
  mobileBreakpoint?: string;
  sidenavCollapsed?: boolean;
  asideOpen?: boolean;
  contentWidth?: "fluid" | "fixed";
  contentPadding?: "none" | "compact" | "comfortable";
  footerMode?: "inline" | "fixed";
  persistKey?: string;
  dark?: boolean;
}

const {
  sidenavMode = "static",
  sidenavLayout = "under-topbar",
  mobileBreakpoint = "(max-width: 991px)",
  contentWidth = "fluid",
  contentPadding = "comfortable",
  footerMode = "inline",
  asideOpen = false,
  dark = false,
  persistKey,
} = defineProps<Props>();

const emit = defineEmits<{
  "update:asideOpen": [value: boolean];
  "shell-change": [state: ShellState];
}>();

const el = ref<TulparShellEl>();

// Resolve the active vue-router instance WITHOUT importing `vue-router`. When an
// app calls `app.use(router)`, vue-router registers itself on the app context's
// globalProperties as `$router` — the very instance `useRouter()` would inject.
// Reading it here keeps vue-router a fully optional peer: a router-less app has
// no `$router`, `router` stays undefined, and the nav-item's native <a>
// navigation takes over. No static import means no module-resolution failure
// when the package isn't installed, and no async/Suspense setup.
const instance = getCurrentInstance();
const router = instance?.appContext.config.globalProperties.$router as RouterLike | undefined;
let removeRouterHook: (() => void) | undefined;
let dispose: (() => void) | undefined;

onMounted(() => {
  if (persistKey && el.value) dispose = persistShellState(el.value, persistKey);
  removeRouterHook = router?.afterEach(() =>
    window.dispatchEvent(new Event("tulpar-location-changed")),
  );
  // Apply the initial dark value once the element ref exists (the watch below
  // only fires on subsequent changes; el.value is still undefined during setup).
  if (el.value) el.value.dark = dark;
});

onBeforeUnmount(() => {
  dispose?.();
  removeRouterHook?.();
});

watch(
  () => dark,
  (v) => {
    if (el.value) el.value.dark = v;
  },
);

function onNavigate(e: Event) {
  if (!router) return; // no router → let native <a> navigation happen
  e.preventDefault();
  router.push((e as CustomEvent).detail.href);
}
</script>

<template>
  <tulpar-shell
    ref="el"
    :sidenav-mode="sidenavMode"
    :sidenav-layout="sidenavLayout"
    :mobile-breakpoint="mobileBreakpoint"
    :sidenav-collapsed="sidenavCollapsed || undefined"
    :aside-open="asideOpen || undefined"
    :content-width="contentWidth"
    :content-padding="contentPadding"
    :footer-mode="footerMode"
    @tulpar-navigate="onNavigate"
    @tulpar-aside-close="emit('update:asideOpen', false)"
    @tulpar-shell-change="emit('shell-change', ($event as CustomEvent).detail)"
  >
    <slot name="topbar" />
    <slot name="sidenav" />
    <slot />
    <slot name="footer" />
    <slot name="aside" />
  </tulpar-shell>
</template>

// packages/angular/src/shell/tulpar-shell.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  DestroyRef,
  ElementRef,
  effect,
  inject,
  input,
  model,
  output,
} from "@angular/core";
import { NavigationEnd, Router } from "@angular/router";

import "@tulpar-ui/shell";
import type { ShellSidenavMode, ShellState, TulparShell } from "@tulpar-ui/shell";
import { persistShellState } from "@tulpar-ui/shell";

export type { ShellSidenavMode, ShellState };

@Component({
  selector: "tulpar-shell-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-shell
      [attr.sidenav-mode]="sidenavMode()"
      [attr.sidenav-layout]="sidenavLayout()"
      [attr.mobile-breakpoint]="mobileBreakpoint()"
      [attr.sidenav-collapsed]="sidenavCollapsed() ? '' : null"
      [attr.aside-open]="asideOpen() ? '' : null"
      [attr.content-width]="contentWidth()"
      [attr.content-padding]="contentPadding()"
      [attr.footer-mode]="footerMode()"
      (tulpar-navigate)="onNavigate($event)"
      (tulpar-aside-close)="asideOpen.set(false)"
      (tulpar-shell-change)="shellChange.emit($any($event).detail)"
    >
      <ng-content select="[slot='topbar']" />
      <ng-content select="[slot='sidenav']" />
      <ng-content />
      <ng-content select="[slot='footer']" />
      <ng-content select="[slot='aside']" />
    </tulpar-shell>
  `,
})
export class TulparShellComponent {
  readonly sidenavMode = input<ShellSidenavMode>("static");
  readonly sidenavLayout = input<"under-topbar" | "over-topbar">("under-topbar");
  readonly mobileBreakpoint = input<string>("(max-width: 991px)");
  readonly sidenavCollapsed = input<boolean>(false);
  readonly asideOpen = model<boolean>(false);
  readonly contentWidth = input<"fluid" | "fixed">("fluid");
  readonly contentPadding = input<"none" | "compact" | "comfortable">("comfortable");
  readonly footerMode = input<"inline" | "fixed">("inline");
  readonly persistKey = input<string | undefined>(undefined);
  readonly dark = input<boolean>(false);
  readonly shellChange = output<ShellState>();

  private readonly router = inject(Router, { optional: true });
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  constructor() {
    // Router → active item update. Subscribing to Router.events (Angular's own
    // Observable API) purely to re-dispatch a DOM event is the only allowed
    // RxJS touch — no state is stored in RxJS. Cleaned up via DestroyRef.
    const sub = this.router?.events.subscribe((e) => {
      if (e instanceof NavigationEnd) {
        window.dispatchEvent(new Event("tulpar-location-changed"));
      }
    });
    this.destroyRef.onDestroy(() => sub?.unsubscribe());

    effect(() => {
      const el = this.host.nativeElement.querySelector<TulparShell>("tulpar-shell");
      if (el) el.dark = this.dark();
    });

    effect((onCleanup) => {
      const key = this.persistKey();
      const el = this.host.nativeElement.querySelector<TulparShell>("tulpar-shell");
      if (key && el) {
        const dispose = persistShellState(el, key);
        onCleanup(dispose);
      }
    });
  }

  onNavigate(e: Event) {
    if (!this.router) return; // no router → native <a> navigation
    e.preventDefault();
    this.router.navigateByUrl((e as CustomEvent).detail.href);
  }
}
