// packages/vue/src/shell/TulparTopbar.vue
<script setup lang="ts">
import "@tulpar-ui/shell";

interface Props {
  showMenuButton?: boolean;
  menuButtonLabel?: string;
}

const { showMenuButton = false, menuButtonLabel } = defineProps<Props>();
</script>

<template>
  <tulpar-topbar
    :show-menu-button="showMenuButton || undefined"
    :menu-button-label="menuButtonLabel ?? undefined"
  >
    <span style="display: contents" slot="start"><slot name="start" /></span>
    <slot />
    <span style="display: contents" slot="end"><slot name="end" /></span>
  </tulpar-topbar>
</template>

// packages/angular/src/shell/tulpar-topbar.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
} from "@angular/core";

import "@tulpar-ui/shell";

@Component({
  selector: "tulpar-topbar-ng",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  styles: [":host { display: contents; }"],
  template: `
    <tulpar-topbar
      [attr.show-menu-button]="showMenuButton() ? '' : null"
      [attr.menu-button-label]="menuButtonLabel() ?? null"
    >
      <ng-content select="[slot='start']" />
      <ng-content />
      <ng-content select="[slot='end']" />
    </tulpar-topbar>
  `,
})
export class TulparTopbarComponent {
  readonly showMenuButton = input<boolean>(false);
  readonly menuButtonLabel = input<string | undefined>(undefined);
}
